import 'package:flutter/material.dart';
class Address{

  var selectedProvience = "Bagmati Pradesh 3";
  var selectedDistrict = "kathmandu";
  var provienceName = {
    'Pradesh 1': 'Provience 1',
    'Madesh Pradesh 2': 'Provience 2',
    'Bagmati Pradesh 3': 'Provience 3',
    'Gandaki Pradesh 4': 'Provience 4',
    'Lumbini Pradesh 5': 'Provience 5',
    'Karnali Pradesh 6': 'Provience 6',
    'Sudurpachim Pradesh 7': 'Provience 7'
  };
  var DistrictName = {
    'Bhojpur '
        'Dhankuta ': 'Provience 1',
    'Ilam ': 'Provience 1',
    'Jhapa ': 'Provience 1',
    'Khotang ': 'Provience 1',
    'Morang ': 'Provience 1',
    'Okhaldhunga ': 'Provience 1',
    'Panchthar ': 'Provience 1',
    'Sankhuwasabha ': 'Provience 1',
    'Solukhumbu ': 'Provience 1',
    'Sunsari': 'Provience 1',
    'Taplejung ': 'Provience 1',
    'Tehrathum ': 'Provience 1',
    'Udayapur': 'Provience 1',
    'Bara ': 'Provience 2',
    'Rautahat ': 'Provience 2',
    'Sarlahi ': 'Provience 2',
    'Dhanusha': 'Provience 2',
    'Siraha ': 'Provience 2',
    'Mahottari ': 'Provience 2',
    'Saptari ': 'Provience 2',
    'Sindhuli ': 'Provience 3',
    'Ramechhap': 'Provience 3',
    'Dolakha': 'Provience 3',
    'Bhaktapur': 'Provience 3',
    'Dhading': 'Provience 3',
    'Kathmandu': 'Provience 3',
    'Kavrepalanchok': 'Provience 3',
    'Lalitpur': 'Provience 3',
    'Nuwakot': 'Provience 3',
    'Rasuwa': 'Provience 3',
    'chitwan': 'Provience 3',
    'Sindhupalchok': 'Provience 3',
    'Baglung ': 'Provience 4',
    'Gorkha ': 'Provience 4',
    'Kaski': 'Provience 4',
    'Lamjung 	': 'Provience 4',
    'Manang ': 'Provience 4',
    'Mustang': 'Provience 4',
    'Myagdi ': 'Provience 4',
    'Nawalpur ': 'Provience 4',
    'Parbat ': 'Provience 4',
    'Syangja ': 'Provience 4',
    'Tanahun ': 'Provience 4',
    'Makwanpur ': 'Provience 4',
    'Kapilvastu': 'Provience 5',
    'Parasi': 'Provience 5',
    'Rupandehi': 'Provience 5',
    'Arghakhanchi': 'Provience 5',
    'Gulmi': 'Provience 5',
    'Palpa': 'Provience 5',
    'Dang': 'Provience 5',
    'Pyuthan': 'Provience 5',
    'Rolpa': 'Provience 5',
    'Eastern Rukum': 'Provience 5',
    'Banke': 'Provience 5',
    'Bardiya': 'Provience 5',
    'Western Rukum': 'Provience 6',
    'Salyan ': 'Provience 6',
    'Dolpa ': 'Provience 6',
    'Humla': 'Provience 6',
    'Jumla': 'Provience 6',
    'Kalikot': 'Provience 6',
    'Mugu': 'Provience 6',
    'Surkhet': 'Provience 6',
    'Dailekh': 'Provience 6',
    'Jajarkot': 'Provience 6',
    'Kailali': 'Provience 7',
    'Achham': 'Provience 7',
    'Doti': 'Provience 7',
    'Bajhang': 'Provience 7',
    'Bajura': 'Provience 7',
    'Kanchanpur': 'Provience 7',
    'Dadeldhura': 'Provience 7',
    'Baitadi': 'Provience 7',
    'Darchula': 'Provience 7',
  };


   List provienceList = <String>[];
   List districtList=<String>[];
}