

import 'package:flutter/material.dart';
class Address{

  var selectedProvience = "Bagmati Pradesh 3";
  var selectedDistrict = "kathmandu";
  var selectedMuncipality='Kathmandu Muncipality';

  var provienceName = {
    'Pradesh 1': 'Provience 1',
    'Madesh Pradesh 2': 'Provience 2',
    'Bagmati Pradesh 3': 'Provience 3',
    'Gandaki Pradesh 4': 'Provience 4',
    'Lumbini Pradesh 5': 'Provience 5',
    'Karnali Pradesh 6': 'Provience 6',
    'Sudurpachim Pradesh 7': 'Provience 7'
  };
  var districtName = {
    'Bhojpur': 'Provience 1',
    'Dhankuta': 'Provience 1',
    'Ilam': 'Provience 1',
    'Jhapa': 'Provience 1',
    'Khotang':'Provience 1',
   'Morang':'Provience 1',
   'Okhaldhunga':'Provience 1',
   'Panchthar':'Provience 1',
   'Sankhuwasabha':'Provience 1',
   'Solukhumbu':'Provience 1',
   'Sunsari':'Provience 1',
   'Taplejung':'Provience 1',
   'Tehrathum':'Provience 1',
   'Udayapur':'Provience 1',
   'Bara':'Provience 2',
   'Rautahat':'Provience 2',
   'Sarlahi':'Provience 2',
   'Dhanusha':'Provience 2',
   'Siraha':'Provience 2',
   'Mahottari':'Provience 2',
   'Saptari':'Provience 2',
   'Sindhuli':'Provience 3',
   'Ramechhap':'Provience 3',
   'Dolakha':'Provience 3',
   'Bhaktapur':'Provience 3',
   'Dhading':'Provience 3',
   'Kathmandu':'Provience 3',
   'Kavrepalanchok':'Provience 3',
   'Lalitpur':'Provience 3',
   'Nuwakot':'Provience 3',
   'Rasuwa':'Provience 3',
   'chitwan':'Provience 3',
   'Sindhupalchok':'Provience 3',
   'Baglung':'Provience 4',
   'Gorkha':'Provience 4',
   'Kaski':'Provience 4',
   'Lamjung 	':'Provience 4',
   'Manang':'Provience 4',
   'Mustang':'Provience 4',
   'Myagdi':'Provience 4',
   'Nawalpur':'Provience 4',
   'Parbat':'Provience 4',
   'Syangja':'Provience 4',
   'Tanahun':'Provience 4',
   'Makwanpur':'Provience 4',
   'Kapilvastu':'Provience 5',
   'Parasi':'Provience 5',
   'Rupandehi':'Provience 5',
   'Arghakhanchi':'Provience 5',
   'Gulmi':'Provience 5',
   'Palpa':'Provience 5',
   'Dang':'Provience 5',
   'Pyuthan':'Provience 5',
   'Rolpa':'Provience 5',
   'Eastern Rukum':'Provience 5',
   'Banke':'Provience 5',
   'Bardiya':'Provience 5',
   'Western Rukum':'Provience 6',
   'Salyan':'Provience 6',
   'Dolpa':'Provience 6',
   'Humla':'Provience 6',
   'Jumla':'Provience 6',
   'Kalikot':'Provience 6',
   'Mugu':'Provience 6',
   'Surkhet':'Provience 6',
   'Dailekh':'Provience 6',
   'Jajarkot':'Provience 6',
   'Kailali':'Provience 7',
   'Achham':'Provience 7',
   'Doti':'Provience 7',
   'Bajhang':'Provience 7',
   'Bajura':'Provience 7',
   'Kanchanpur':'Provience 7',
   'Dadeldhura':'Provience 7',
   'Baitadi':'Provience 7',
   'Darchula':'Provience 7',
  };



  var muncipalityName ={
'Sidingba Rural Municipality' :'Taplejung',
 'Meringden Rural Municipality' :'Taplejung',
 'Maiwakhola Rural Municipality' :'Taplejung',
 'Phaktanglung Rural Municipality' :'Taplejung',
  'Sirijangha Rural Municipality' : 'Taplejung',
  'Mikwakhola Rural Municipality'  : 'Taplejung',
  'Aathrai Tribeni Rural Municipality'  : 'Taplejung',
  'Pathivara Yangwarak Rural Municipality'  : 'Taplejung',
  'Phungling Municipality'  : 'Taplejung',
  'Makalu Rural Municipality'  : 'Sankhuwasabha',
  'Chichila Rural Municipality'  : 'Sankhuwasabha',
  'Silichong Rural Municipality'  : 'Sankhuwasabha',
  'Bhotkhola Rural Municipality': 'Sankhuwasabha',
  'Sabhapokhari Rural Municipality' : 'Sankhuwasabha',
  'Dharmadevi Municipality' : 'Sankhuwasabha',
  'Madi Municipality' : 'Sankhuwasabha',
  'Panchakhapan Municipality' : 'Sankhuwasabha',
  'Chainpur Municipality' : 'Sankhuwasabha',
  'Khandbari Municipality' : 'Sankhuwasabha',
  'Sotang Rural Municipality' : 'Solukhumbu',
  'Mahakulung Rural Municipality' : 'Solukhumbu',
  'Likhupike Rural Municipality' : 'Solukhumbu',
  'Nechasalyan Rural Municipality' : 'Solukhumbu',
  'Thulung Dudhkoshi Rural Municipality' : 'Solukhumbu',
  'Maapya Dudhkoshi Rural Municipality' : 'Solukhumbu',
  'Khumbupasanglahmu Rural Municipality' : 'Solukhumbu',
  'Solududhakunda Municipality' : 'Solukhumbu',
  'Likhu Rural Municipality' : 'Okhaldhunga',
  'Molung Rural Municipality' : 'Okhaldhunga',
  'Sunkoshi Rural Municipality' : 'Okhaldhunga',
  'Champadevi Rural Municipality' : 'Okhaldhunga',
  'Chisankhugadhi Rural Municipality' : 'Okhaldhunga',
  'Khijidemba Rural Municipality' : 'Okhaldhunga',
  'Manebhanjyang Rural Municipality' : 'Okhaldhunga',
  'Siddhicharan Municipality' : 'Okhaldhunga',
  'Sakela Rural Municipality' : 'Khotang',
  'Khotehang Rural Municipality' : 'Khotang',
  'Barahapokhari Rural Municipality' : 'Khotang',
  'Ainselukhark Rural Municipality' : 'Khotang',
  'Rawa Besi Rural Municipality' : 'Khotang',
  'Kepilasagadhi Rural Municipality' : 'Khotang',
  'Jantedhunga Rural Municipality' : 'Khotang',
  'Diprung Chuichumma Rural Municipality' : 'Khotang',
  'Halesi Tuwachung Municipality' : 'Khotang',
  'Diktel Rupakot Majhuwagadhi Municipality' : 'Khotang',
  'Arun Rural Municipality' : 'Bhojpur',
  'Aamchowk Rural Municipality' : 'Bhojpur',
  'Hatuwagadhi Rural Municipality' : 'Bhojpur',
  'Pauwadungma Rural Municipality' : 'Bhojpur',
  'Temkemaiyung Rural Municipality' : 'Bhojpur',
  'Salpasilichho Rural Municipality' : 'Bhojpur',
    'Ramprasad Rai Rural Municipality' : 'Bhojpur',
  'Shadananda Municipality' : 'Bhojpur',
  'Bhojpur Municipality' : 'Bhojpur',
  'Chaubise Rural Municipality' : 'Dhankuta',
  'Shahidbhumi Rural Municipality' : 'Dhankuta',
  'Sangurigadhi Rural Municipality' : 'Dhankuta',
  'Chhathar Jorpati Rural Municipality' : 'Dhankuta',
  'Pakhribas Municipality' : 'Dhankuta',
  'Mahalaxmi Municipality' : 'Dhankuta',
  'Dhankuta Municipality' : 'Dhankuta',
  'Chhathar Rural Municipality' : 'Terhathum ',
  'Phedap Rural Municipality' : 'Terhathum ',
  'Aathrai Rural Municipality' : 'Terhathum ',
  'Menchayam Rural Municipality' : 'Terhathum ',
  'Laligurans Municipality' : 'Terhathum ',
  'Myanglung Municipality' : 'Terhathum ',
  'Yangwarak Rural Municipality' : 'Panchthar',
  'Hilihang Rural Municipality' : 'Panchthar',
  'Falelung Rural Municipality' : 'Panchthar',
  'Tumbewa Rural Municipality' : 'Panchthar',
  'Kummayak Rural Municipality' : 'Panchthar',
  'Miklajung Rural Municipality (Pachthar)' : 'Panchthar',
  'Falgunanda Rural Municipality' : 'Panchthar',
  'Phidim Municipality' : 'Panchthar',
  'Rong Rural Municipality' : 'Ilam',
  'Mangsebung Rural Municipality' : 'Ilam',
  'Chulachuli Rural Municipality' : 'Ilam',
  'Sandakpur Rural Municipality' : 'Ilam',
  'Fakphokthum Rural Municipality' : 'Ilam',
  'Maijogmai Rural Municipality' : 'Ilam',
  'Illam Municipality' : 'Ilam',
  'Mai Municipality' : 'Ilam',
  'Deumai Municipality' : 'Ilam',
  'Suryodaya Municipality' : 'Ilam',
  'Kamal Rural Municipality' : 'Jhapa',
  'Jhapa Rural Municipality' : 'Jhapa',
  'Kachankawal Rural Municipality' : 'Jhapa',
  'Gauriganj Rural Municipality' : 'Jhapa',
  'Barhadashi Rural Municipality' : 'Jhapa',
  'Haldibari Rural Municipality' : 'Jhapa',
  'Buddhashanti Rural Municipality' : 'Jhapa',
  'Shivasataxi Municipality' : 'Jhapa',
  'Bhadrapur Municipality' : 'Jhapa',
  'Kankai Municipality' : 'Jhapa',
  'Birtamod Municipality' : 'Jhapa',
  'Mechinagar Municipality' : 'Jhapa',
  'Damak Municipality' : 'Jhapa',
  'Arjundhara Municipality' : 'Jhapa',
  'Gauradhaha Municipality' : 'Jhapa',
  'Jahada Rural Municipality' : 'Morang',
    'Katahari Rural Municipality' : 'Morang',
  'Gramthan Rural Municipality' : 'Morang',
  'Dhanpalthan Rural Municipality' : 'Morang',
  'Kerabari Rural Municipality' : 'Morang',
  'Budhiganga Rural Municipality' : 'Morang',
  'Kanepokhari Rural Municipality' : 'Morang',
  'Miklajung Rural Municipality' : 'Morang',
  'Letang Municipality' : 'Morang',
  'Sunwarshi Municipality' : 'Morang',
  'Rangeli Municipality' : 'Morang',
  'Patahrishanishchare Municipality' : 'Morang',
  'Biratnagar Metropolitian City' : 'Morang',
  'Uralabari Municipality' : 'Morang',
  'Belbari Municipality' : 'Morang',
  'Sundarharaicha Municipality' : 'Morang',
  'Ratuwamai Municipality' : 'Morang',
  'Gadhi Rural Municipality' : 'Sunsari',
  'Koshi Rural Municipality' : 'Sunsari',
  'Barju Rural Municipality' : 'Sunsari',
  'Harinagar Rural Municipality' : 'Sunsari',
  'Dewanganj Rural Municipality' : 'Sunsari',
  'Bhokraha Narsing Rural Municipality' : 'Sunsari',
  'Ramdhuni Municipality' : 'Sunsari',
  'Barahchhetra Municipality' : 'Sunsari',
  'Duhabi Municipality' : 'Sunsari',
    'Inaruwa Municipality' : 'Sunsari',
  'Dharan Sub-Metropolitian City ' : 'Sunsari',
  'Itahari Sub-Metropolitian City' : 'Sunsari',
  'Tapli Rural Municipality' : 'Udayapur',
  'Rautamai Rural Municipality' : 'Udayapur',
  'Udayapur Gadhi Rural Municipality' : 'Udayapur',
  'Limchungbung Rural Municipality' : 'Udayapur',
  'Chaudandigadhi Municipality' : 'Udayapur',
  'Triyuga Municipality' : 'Udayapur',
  'Katari Municipality' : 'Udayapur',
  'Belaka Municipality' : 'Udayapur',
  'Rajgadh Rural Municipality' : 'Saptari',
  'Rupani Rural Municipality' : 'Saptari',
  'Tirahut Rural Municipality' : 'Saptari',
  'Mahadeva Rural Municipality' : 'Saptari',
  'Bishnupur Rural Municipality' : 'Saptari',
  'Chhinnamasta Rural Municipality' : 'Saptari',
  'Balan Bihul Rural Municipality' : 'Saptari',
  'Tilathi Koiladi Rural Municipality' : 'Saptari',
  'Agnisair Krishna Municipality' : 'Saptari',
  'Hanumannagar Kankalini Municipality' : 'Saptari',
  'Kanchanrup Municipality' : 'Saptari',
  'Rajbiraj Municipality' : 'Saptari',
  'Khadak Municipality' : 'Saptari',
  'Dakneshwori Municipality' : 'Saptari',
  'Saptakoshi Rural Municipality' : 'Saptari',
  'Surunga Municipality' : 'Saptari',
  'Shambhunath Municipality' : 'Saptari',
  'Bode Barsain Municipality' : 'Saptari',
  'Aurahi Rural Municipality' : 'Siraha',
  'Naraha Rural Municipality' : 'Siraha',
  'Arnama Rural Municipality' : 'Siraha',
  'Bhagawanpur Rural Municipality' : 'Siraha',
  'Nawarajpur Rural Municipality' : 'Siraha',
  'Bishnupur Rural Municipality (Siraha)' : 'Siraha',
  'Bariyarpatti Rural Municipality' : 'Siraha',
  'Laxmipur Patari Rural Municipality' : 'Siraha',
  'Sakhuwanankarkatti Rural Municipality' : 'Siraha',
  'Mirchaiya Municipality' : 'Siraha',
  'Lahan Municipality' : 'Siraha',
  'Siraha Municipality' : 'Siraha',
  'Dhangadhimai Municipality' : 'Siraha',
  'Kalyanpur Municipality' : 'Siraha',
  'Karjanha Municipality' : 'Siraha',
  'Golbazar Municipality' : 'Siraha',
  'Sukhipur Municipality' : 'Siraha',
  'Aaurahi Rural Municipality' : 'Dhanusha',
  'Dhanauji Rural Municipality' : 'Dhanusha',
  'Bateshwor Rural Municipality' : 'Dhanusha',
  'Janaknandani Rural Municipality' : 'Dhanusha',
    'Lakshminiya Rural Municipality' : 'Dhanusha',
  'Mukhiyapatti Musarmiya Rural Municipality' : 'Dhanusha',
  'Mithila Bihari Municipality' : 'Dhanusha',
  'Kamala Municipality' : 'Dhanusha',
  'Nagarain Municipality' : 'Dhanusha',
  'Ganeshman Charnath Municipality' : 'Dhanusha',
  'Mithila Municipality' : 'Dhanusha',
  'Dhanusa Dham Municipality' : 'Dhanusha',
  'Bideha Municipality' : 'Dhanusha',
  'Sabaila Municipality' : 'Dhanusha',
  'Hansapur Municipality' : 'Dhanusha',
  'Janakpurdham Sub-Metropolitian City ' : 'Dhanusha',
  'Sahidnagar Municipality' : 'Dhanusha',
  'Chhireshwornath Municipality' : 'Dhanusha',
  'Pipra Rural Municipality' : 'Mahottari',
  'Sonama Rural Municipality' : 'Mahottari',
  'Samsi Rural Municipality' : 'Mahottari',
  'Ekdanra Rural Municipality' : 'Mahottari',
  'Mahottari Rural Municipality' : 'Mahottari',
  'Gaushala Municipality' : 'Mahottari',
  'Ramgopalpur Municipality' : 'Mahottari',
  'Aurahi Municipality' : 'Mahottari',
  'Bardibas Municipality' : 'Mahottari',
  'Bhangaha Municipality' : 'Mahottari',
  'Jaleswor Municipality' : 'Mahottari',
  'Balwa Municipality' : 'Mahottari',
  'Manra Siswa Municipality' : 'Mahottari',
  'Matihani Municipality' : 'Mahottari',
  'Loharpatti Municipality' : 'Mahottari',
  'Dhankaul Rural Municipality' : 'Sarlahi',
  'Parsa Rural Municipality' : 'Sarlahi',
  'Bishnu Rural Municipality' : 'Sarlahi',
  'Ramnagar Rural Municipality' : 'Sarlahi',
  'Kaudena Rural Municipality': 'Sarlahi',
  'Basbariya Rural Municipality' : 'Sarlahi',
  'Chandranagar Rural Municipality' : 'Sarlahi',
  'Chakraghatta Rural Municipality' : 'Sarlahi',
  'Bramhapuri Rural Municipality' : 'Sarlahi',
  'Barahathawa Municipality' : 'Sarlahi',
  'Haripur Municipality' : 'Sarlahi',
  'Ishworpur Municipality' : 'Sarlahi',
  'Lalbandi Municipality' : 'Sarlahi',
  'Malangawa Municipality' : 'Sarlahi',
  'Kabilasi Municipality' : 'Sarlahi',
  'Bagmati Municipality' : 'Sarlahi',
  'Hariwan Municipality' : 'Sarlahi',
  'Balara Municipality' : 'Sarlahi',
  'Haripurwa Municipality' : 'Sarlahi',
  'Godaita Municipality' : 'Sarlahi',
  'Yemunamai Rural Municipality' : 'Rautahat',
  'Durga Bhagwati Rural Municipality' : 'Rautahat',
  'Katahariya Municipality' : 'Rautahat',
  'Maulapur Municipality' : 'Rautahat',
  'Madhav Narayan Municipality' : 'Rautahat',
  'Gaur Municipality' : 'Rautahat',
  'Gujara Municipality' : 'Rautahat',
  'Garuda Municipality': 'Rautahat',
  ' Ishanath Municipality':'Rautahat',
  'Chandrapur Municipality' : 'Rautahat',
  'Dewahhi Gonahi Municipality' : 'Rautahat',
  'Brindaban Municipality' : 'Rautahat',
  'Rajpur Municipality' : 'Rautahat',
  'Rajdevi Municipality' : 'Rautahat',
  'Gadhimai Municipality' : 'Rautahat',
  'Phatuwa Bijayapur Municipality' : 'Rautahat',
  'Baudhimai Municipality' : 'Rautahat',
  'Paroha Municipality' : 'Rautahat',
  'Pheta Rural Municipality' : 'Bara',
  'Devtal Rural Municipality' : 'Bara',
  'Prasauni Rural Municipality' : 'Bara',
  'Suwarna Rural Municipality' : 'Bara',
  'Baragadhi Rural Municipality' : 'Bara',
  'Karaiyamai Rural Municipality' : 'Bara',
  'Parwanipur Rural Municipality' : 'Bara',
  'Bishrampur Rural Municipality' : 'Bara',
  'Adarshkotwal Rural Municipality' : 'Bara',
  'Jitpur Simara Sub-Metropolitian City ' : 'Bara',
  'Kalaiya Sub-Metropolitian City' : 'Bara',
    'Pacharauta Municipality' : 'Bara',
  'Nijgadh Municipality' : 'Bara',
  'Simraungadh Municipality' : 'Bara',
  'Mahagadhimai Municipality' : 'Bara',
  'Kolhabi Municipality' : 'Bara',
  'Thori Rural Municipality' : 'Parsa',
  'Dhobini Rural Municipality' : 'Parsa',
  'Chhipaharmai Rural Municipality' : 'Parsa',
  'Jirabhawani Rural Municipality' : 'Parsa',
  'Jagarnathpur Rural Municipality' : 'Parsa',
  'Kalikamai Rural Municipality' : 'Parsa',
  'Bindabasini Rural Municipality' : 'Parsa',
  'Pakahamainpur Rural Municipality' : 'Parsa',
  'Sakhuwaprasauni Rural Municipality' : 'Parsa',
  'Paterwasugauli Rural Municipality' : 'Parsa',
  'Birgunj Metropolitian City ' : 'Parsa',
  'Bahudaramai Municipality' : 'Parsa',
  'Pokhariya Municipality' : 'Parsa',
  'Parsagadhi Municipality' : 'Parsa',
  'Bigu Rural Municipality' : 'Dolakha',
  'Jiri Municipality': 'Dolakha',
  'Sailung Rural Municipality' : 'Dolakha',
  'Melung Rural Municipality' : 'Dolakha',
  'Baiteshwor Rural Municipality' : 'Dolakha',
  'Tamakoshi Rural Municipality' : 'Dolakha',
  'Gaurishankar Rural Municipality' : 'Dolakha',
    'Kalinchok Rural Municipality' : 'Dolakha',
  'Bhimeshwor Municipality' : 'Dolakha',
  'Jugal Rural Municipality' : 'Sindhupalchok',
  'Balefi Rural Municipality' : 'Sindhupalchok',
  'Sunkoshi Rural Municipality(Sindhupalchok)' : 'Sindhupalchok',
  'Helambu Rural Municipality' : 'Sindhupalchok',
  'Bhotekoshi Rural Municipality' : 'Sindhupalchok',
  'Lisangkhu Pakhar Rural Municipality' : 'Sindhupalchok',
  'Indrawati Rural Municipality' : 'Sindhupalchok',
  'Tripurasundari Rural Municipality' : 'Sindhupalchok',
  'Panchpokhari Thangpal Rural Municipality' : 'Sindhupalchok',
  'Chautara Sangachokgadhi Municipality' : 'Sindhupalchok',
  'Barhabise Municipality' : 'Sindhupalchok',
  'Melamchi Municipality' : 'Sindhupalchok',
  'Kalika Rural Municipality' : 'Rasuwa',
  'Naukunda Rural Municipality' : 'Rasuwa',
  'Uttargaya Rural Municipality' : 'Rasuwa',
  'Gosaikunda Rural Municipality' : 'Rasuwa',
  'Amachodingmo Rural Municipality' : 'Rasuwa',
  'Gajuri Rural Municipality' : 'Dhading',
 ' Thakre Rural Municipality': 'Dhading',
  'Galchi Rural Municipality' : 'Dhading',
  'Siddhalek Rural Municipality' : 'Dhading',
  'Khaniyabash Rural Municipality' : 'Dhading',
  'Jwalamukhi Rural Municipality' : 'Dhading',
  'Gangajamuna Rural Municipality' : 'Dhading',
  'Rubi Valley Rural Municipality' : 'Dhading',
  'Tripura Sundari Rural Municipality' : 'Dhading',
  'Netrawati Dabjong Rural Municipality' : 'Dhading',
  'Benighat Rorang Rural Municipality' : 'Dhading',
  'Nilakantha Municipality' : 'Dhading',
  'Dhunibesi Municipality' : 'Dhading',
  'Kakani Rural Municipality' : 'Nuwakot',
  'Tadi Rural Municipality' : 'Nuwakot',
  'Likhu Rural Municipality(Nuwakot)' : 'Nuwakot',
  'Myagang Rural Municipality' : 'Nuwakot',
  'Shivapuri Rural Municipality' : 'Nuwakot',
  'Kispang Rural Municipality' : 'Nuwakot',
  'Suryagadhi Rural Municipality' : 'Nuwakot',
  'Tarkeshwar Rural Municipality' : 'Nuwakot',
  'Panchakanya Rural Municipality' : 'Nuwakot',
  'Dupcheshwar Rural Municipality' : 'Nuwakot',
  'Belkotgadhi Municipality' : 'Nuwakot',
  'Bidur Municipality' : 'Nuwakot',
  'Kirtipur Municipality' : 'Kathmandu',
  'Shankharapur Municipality' : 'Kathmandu',
  'Shankharapur Municipality(Kathmandu)' : 'Kathmandu',
  'Nagarjun Municipality' : 'Kathmandu',
  'Kageshwori Manahora Municipality' : 'Kathmandu',
  'Dakshinkali Municipality' : 'Kathmandu',
  'Budhanilakantha Municipality' : 'Kathmandu',
    'Tarakeshwor Municipality' : 'Kathmandu',
  'Kathmandu  Metropolitian City ' : 'Kathmandu',
  'Tokha Municipality' : 'Kathmandu',
  'Chandragiri Municipality' : 'Kathmandu',
  'Gokarneshwor Municipality' : 'Kathmandu',
  'Changunarayan Municipality' : 'Bhaktapur',
  'Suryabinayak Municipality' : 'Bhaktapur',
  'Bhaktapur Municipality' : 'Bhaktapur',
  'Madhyapur Thimi Municipality' : 'Bhaktapur',
  'Bagmati Rural Municipality' : 'Lalitpur',
  'Mahankal Rural Municipality' : 'Lalitpur',
  'Konjyosom Rural Municipality' : 'Lalitpur',
  'Lalitpur  Metropolitian City' : 'Lalitpur',
  'Mahalaxmi Municipality(Lalitpur)' : 'Lalitpur',
  'Godawari Municipality' : 'Lalitpur',
  'Roshi Rural Municipality' : 'Kavrepalanchok',
  'Temal Rural Municipality' : 'Kavrepalanchok',
  'Bhumlu Rural Municipalit' : 'Kavrepalanchok',
  'Mahabharat Rural Municipality' : 'Kavrepalanchok',
  'Bethanchowk Rural Municipality' : 'Kavrepalanchok',
  'Khanikhola Rural Municipality' : 'Kavrepalanchok',
  'Chaurideurali Rural Municipality': 'Kavrepalanchok',
  'Banepa Municipality' : 'Kavrepalanchok',
  'Mandandeupur Municipality' : 'Kavrepalanchok',
  'Dhulikhel Municipality' : 'Kavrepalanchok',
    'Panauti Municipality' : 'Kavrepalanchok',
  'Namobuddha Municipality  ' : 'Kavrepalanchok',
  'Panchkhal Municipality' : 'Kavrepalanchok',
  'Sunapati Rural Municipality' : 'Ramechhap',
  'Doramba Rural Municipality' : 'Ramechhap',
  'Umakunda Rural Municipality' : 'Ramechhap',
  'Khadadevi Rural Municipality' : 'Ramechhap',
  'Gokulganga Rural Municipality' : 'Ramechhap',
  'Likhu Tamakoshi Rural Municipality' : 'Ramechhap',
  'Manthali Municipality' : 'Ramechhap',
  'Ramechhap Municipality' : 'Ramechhap',
  'Marin Rural Municipality' : 'Sindhuli',
  'Golanjor Rural Municipality': 'Sindhuli',
  'Phikkal Rural Municipality' : 'Sindhuli',
  'Tinpatan Rural Municipality' : 'Sindhuli',
  'Sunkoshi Rural Municipality(Sindhuli)' : 'Sindhuli',
  'Ghanglekh Rural Municipality' : 'Sindhuli',
  'Hariharpurgadhi Rural Municipality' : 'Sindhuli',
  'Dudhouli Municipality' : 'Sindhuli',
  'Kamalamai Municipality' : 'Sindhuli',
  'Bakaiya Rural Municipality' : 'Makwanpur',
  'Kailash Rural Municipality' : 'Makwanpur',
  'Manahari Rural Municipality' : 'Makwanpur',
  'Bhimphedi Rural Municipality' : 'Makwanpur',
  'Bagmati Rural Municipality(Makwanpur)' : 'Makwanpur',
  'Raksirang Rural Municipality' : 'Makwanpur',
  'Makawanpurgadhi Rural Municipality' : 'Makwanpur',
  'Indrasarowar Rural Municipality' : 'Makwanpur',
  'Hetauda Sub-Metropolitian City ' : 'Makwanpur',
  'Thaha Municipality' : 'Makwanpur',
  'Ichchhyakamana Rural Municipality' : 'Chitawan',
  'Bharatpur Metropolitian City' : 'Chitawan',
  'Kalika Municipality' : 'Chitawan',
  'Khairahani Municipality' : 'Chitawan',
  'Madi Municipality (Chitwan)' : 'Chitawan',
  'Rapti Municipality' : 'Chitawan',
  'Ratnanagar Municipality' : 'Chitawan',
  'Gandaki Rural Municipality' : 'Gorkha',
  'Dharche Rural Municipality' : 'Gorkha',
  'Aarughat Rural Municipality' : 'Gorkha',
  'Ajirkot Rural Municipality' : 'Gorkha',
  'Sahid Lakhan Rural Municipality' : 'Gorkha',
  'Siranchok Rural Municipality' : 'Gorkha',
  'Bhimsenthapa Rural Municipality' : 'Gorkha',
  'Chum Nubri Rural Municipality' : 'Gorkha',
  'Barpak Sulikot Rural Municipality' : 'Gorkha',
  'Palungtar Municipality' : 'Gorkha',
  'Gorkha Municipality' : 'Gorkha',
  'Chame Rural Municipality' : 'Manang',
  'Narshon Rural Municipality' : 'Manang',
  'Narpa Bhumi Rural Municipality' : 'Manang',
  'Manang Ingshyang Rural Municipality' : 'Manang',
  'Thasang Rural Municipality' : 'Mustang',
  'Gharapjhong Rural Municipality' : 'Mustang',
  'Lomanthang Rural Municipality' : 'Mustang',
  'Lo-Ghekar Damodarkunda Rural Municipality' : 'Mustang',
  'Waragung Muktikhsetra Rural Municipality' : 'Mustang',
  'Mangala Rural Municipality' : 'Myagdi',
  'Malika Rural Municipality' : 'Myagdi',
  'Raghuganga Rural Municipality' : 'Myagdi',
  'Dhaulagiri Rural Municipality' : 'Myagdi',
  'Annapurna Rural Municipality' : 'Myagdi',
  'Beni Municipality' : 'Myagdi',
  'Rupa Rural Municipality' : 'Kaski',
  'Madi Rural Municipality' : 'Kaski',
  'Annapurna Rural Municipality (Kaski)' : 'Kaski',
  'Machhapuchchhre Rural Municipality': 'Kaski',
  'Pokhara Metropolitian City' : 'Kaski',
  'Dordi Rural Municipality' : 'Lamjung',
  'Dudhpokhari Rural Municipality' : 'Lamjung',
  'Marsyangdi Rural Municipality': 'Lamjung',
  'Kwholasothar Rural Municipality' : 'Lamjung',
  'Sundarbazar Municipality' : 'Lamjung',
  'Besishahar Municipality' : 'Lamjung',
  'Rainas Municipality' : 'Lamjung',
  'Madhyanepal Municipality' : 'Lamjung',
  'Ghiring Rural Municipality' : 'Tanahu',
  'Devghat Rural Municipality' : 'Tanahu',
  'Rhishing Rural Municipality' : 'Tanahu',
  'Myagde Rural Municipality' : 'Tanahu',
  'Bandipur Rural Municipality' : 'Tanahu',
  'Byas Municipality' : 'Tanahu',
  'Anbukhaireni Rural Municipality' : 'Tanahu',
  'Shuklagandaki Municipality' : 'Tanahu',
  'Bhimad Municipality' : 'Tanahu',
  'Bhanu Municipality' : 'Tanahu',
  'Baudeekali Rural Municipality' : 'Eastern Nawalparasi  ',
  'East Bulingtar Rural Municipality' : 'Eastern Nawalparasi ',
  'East Hupsekot Rural Municipality' : 'Eastern Nawalparasi ',
  'East Binayee Tribeni Rural Municipality' : 'Eastern Nawalparasi ',
  'East Madhyabindu Municipality' : 'Eastern Nawalparasi ',
  'East Devchuli Municipality' : 'Eastern Nawalparasi ',
  'East Gaidakot Municipality' : 'Eastern Nawalparasi ',
  'East Kawasoti Municipality' : 'Eastern Nawalparasi ',
  'Harinas Rural Municipality' : 'Syangja',
  'Biruwa Rural Municipality' : 'Syangja',
  'Aandhikhola Rural Municipality' : 'Syangja',
  'Phedikhola Rural Municipality' : 'Syangja',
  'Kaligandagi Rural Municipality' : 'Syangja',
  'Arjunchaupari Rural Municipality' : 'Syangja',
  'Putalibazar Municipality' : 'Syangja',
  'Bhirkot Municipality' : 'Syangja',
  'Galyang Municipality' : 'Syangja',
  'Chapakot Municipality' : 'Syangja',
  'Waling Municipality' : 'Syangja',
  'Modi Rural Municipality' : 'Parbat',
  'Painyu Rural Municipality' : 'Parbat',
  'Jaljala Rural Municipality' : 'Parbat',
  'Bihadi Rural Municipality' : 'Parbat',
  'Mahashila Rural Municipality' : 'Parbat',
  'Kushma Municipality' : 'Parbat',
  'Phalebas Municipality' : 'Parbat',
  'Bareng Rural Municipality' : 'Baglung',
  'Tara Khola Rural Municipality': 'Baglung',
  'Badigad Rural Municipality' : 'Baglung',
  'Nisikhola Rural Municipality' : 'Baglung',
  'Kanthekhola Rural Municipality' : 'Baglung',
  'Taman Khola Rural Municipality' : 'Baglung',
  'Jaimuni Municipality' : 'Baglung',
  'Baglung Municipality' : 'Baglung',
  'Galkot Municipality' : 'Baglung',
  'Dhorpatan Municipality' : 'Baglung',
  'East Bhume Rural Municipality' : 'Eastern Rukum',
  'East Sisne Rural Municipality' : 'Eastern Rukum',
  'East Putha Uttarganga Rural Municipality' : 'Eastern Rukum',
  'Madi Rural Municipality(Rolpa)' : 'Ropla',
  'Thawang Rural Municipality' : 'Rolpa',
  'Sunchhahari Rural Municipality' : 'Rolpa',
  'Lungri Rural Municipality' : 'Rolpa',
  'Gangadev Rural Municipality' : 'Rolpa',
  'Tribeni Rural Municipality (Ropla)' : 'Rolpa',
  'Pariwartan Rural Municipality' : 'Rolpa',
  'Runtigadi Rural Municipality' : 'Rolpa',
  'Sunil Smriti Rural Municipality' : 'Rolpa',
  'Rolpa Municipality' : 'Rolpa',
  'Ayirabati Rural Municipality' : 'Pyuthan',
  'Gaumukhi Rural Municipality' : 'Pyuthan',
  'Jhimruk Rural Municipality' : 'Pyuthan',
  'Naubahini Rural Municipality' : 'Pyuthan',
  'Mandavi Rural Municipality' : 'Pyuthan',
  'Mallarani Rural Municipality' : 'Pyuthan',
  'Sarumarani Rural Municipality' : 'Pyuthan',
  'Pyuthan Municipality' : 'Pyuthan',
  'Sworgadwary Municipality' : 'Pyuthan',
  'Ruru Rural Municipality' : 'Gulmi',
  'Isma Rural Municipality' : 'Gulmi',
  'Madane Rural Municipality' : 'Gulmi',
  'Malika Rural Municipality(Gulmi)' : 'Gulmi',
  'Chatrakot Rural Municipality' : 'Gulmi',
  'Dhurkot Rural Municipality' : 'Gulmi',
  'Satyawati Rural Municipality' : 'Gulmi',
  'Chandrakot Rural Municipality' : 'Gulmi',
  'Kaligandaki Rural Municipality' : 'Gulmi',
  'Gulmi Darbar Rural Municipality' : 'Gulmi',
  'Resunga Municipality' : 'Gulmi',
  'Musikot Municipality' : 'Gulmi',
  'Panini Rural Municipality' : 'Arghakhanchi',
  'Chhatradev Rural Municipality' : 'Arghakhanchi',
  'Malarani Rural Municipality' : 'Arghakhanchi',
  'Bhumekasthan Municipality' : 'Arghakhanchi',
  'Sitganga Municipality' : 'Arghakhanchi',
  'Sandhikharka Municipality' : 'Arghakhanchi',
  'Rambha Rural Municipality' : 'Palpa',
  'Tinau Rural Municipality' : 'Palpa',
  'Nisdi Rural Municipality' : 'Palpa',
  'Mathagadhi Rural Municipality' : 'Palpa',
  'Ribdikot Rural Municipality' : 'Palpa',
  'Purbakhola Rural Municipality' : 'Palpa',
  'Bagnaskali Rural Municipality' : 'Palpa',
  'Rainadevi Chhahara Rural Municipality' : 'Palpa',
  'Tansen Municipality' : 'Palpa',
  'Ampur Municipality' : 'Palpa',
  'West Sarawal Rural Municipality' : 'Western Nawalparasi',
  'West Susta Rural Municipality' : 'Western Nawalparasi',
  'West Pratappur Rural Municipality' :'Western Nawalparasi',
  'West Palhi Nandan Rural Municipality' : 'Western Nawalparasi',
  'West Bardaghat Municipality' : 'Western Nawalparasi',
  'West Sunwal Municipality' : 'Western Nawalparasi',
  'West Ramgram Municipality' :'Western Nawalparasi',
  'Kanchan Rural Municipality' : 'Rupandehi',
  'Siyari Rural Municipality' : 'Rupandehi',
  'Rohini Rural Municipality' : 'Rupandehi',
  'Gaidahawa Rural Municipality' : 'Rupandehi',
  'Omsatiya Rural Municipality' : 'Rupandehi',
  'Sudhdhodhan Rural Municipality' : 'Rupandehi',
  'Mayadevi Rural Municipality' : 'Rupandehi',
  'Marchawari Rural Municipality' : 'Rupandehi',
  'Kotahimai Rural Municipality' : 'Rupandehi',
  'Sammarimai Rural Municipality' : 'Rupandehi',
  'Butwal Sub-Metropolitian City' : 'Rupandehi',
  'Lumbini Sanskritik Municipality' : 'Rupandehi',
  'Devdaha Municipality' : 'Rupandehi',
  'Sainamaina Municipality' : 'Rupandehi',
  'Siddharthanagar Municipality' : 'Rupandehi',
  'Tillotama Municipality' : 'Rupandehi',
  'Yashodhara Rural Municipality' : 'Kapilbastu',
  'Bijayanagar Rural Municipality' : 'Kapilbastu',
  'Mayadevi Rural Municipality(Kalilbastu)' : 'Kapilbastu',
  'Suddhodhan Rural Municipality' : 'Kapilbastu',
  'Shivaraj Municipality' : 'Kapilbastu',
  'Kapilbastumunicipality' : 'Kapilbastu',
  'Buddhabhumi Municipality' : 'Kapilbastu',
  'Maharajgunj Municipality' : 'Kapilbastu',
  'Banganga Municipality' : 'Kapilbastu',
  'Krishnanagar Municipality' : 'Kapilbastu',
  'Babai Rural Municipality' : 'Dang',
  'Gadhawa Rural Municipality' : 'Dang',
  'Rapti Rural Municipality' : 'Dang',
  'Rajpur Rural Municipality' : 'Dang',
  'Dang Isharan Rural Municipality' : 'Dang',
  'Shantinagar Rural Municipality' : 'Dang',
  'Banglachuli Rural Municipality' : 'Dang',
  'Tulsipur Sub-Metropolitian City' : 'Dang',
  'Ghorahi Sub-Metropolitian City' : 'Dang',
  'Lamahi Municipality' : 'Dang',
  'Khajura Rural Municipality' : 'Banke',
  'Kohalpur Municipality':'Banke',
  'Janki Rural Municipality' : 'Banke',
  'Baijanath Rural Municipality' : 'Banke',
  'Duduwa Rural Municipality' : 'Banke',
  'Narainapur Rural Municipality' : 'Banke',
  'Rapti Sonari Rural Municipality' : 'Banke',
  'Nepalgunj Sub-Metropolitian City' : 'Banke',
  'Geruwa Rural Municipality' : 'Bardiya',
  'Badhaiyatal Rural Municipality' : 'Bardiya',
  'Thakurbaba Municipality' : 'Bardiya',
  'Bansagadhi Municipality' : 'Bardiya',
  'Barbardiya Municipality' : 'Bardiya',
  'Rajapur Municipality' : 'Bardiya',
  'Madhuwan Municipality' : 'Bardiya',
  'Gulariya Municipality' : 'Bardiya',
  'Kaike Rural Municipality' : 'Dolpa',
  'Jagadulla Rural Municipality' : 'Dolpa',
  'Mudkechula Rural Municipality' : 'Dolpa',
  'Dolpo Buddha Rural Municipality' : 'Dolpa',
  'Shey Phoksundo Rural Municipality' : 'Dolpa',
  'Chharka Tangsong Rural Municipality' : 'Dolpa',
  'Tripurasundari Municipality' : 'Dolpa',
  'Thuli Bheri Municipality' : 'Dolpa',
  'Soru Rural Municipality' : 'Mugu',
  'Khatyad Rural Municipality' : 'Mugu',
  'Mugu Karmarong Rural Municipality' : 'Mugu',
  'Chhayanath Rara Municipality' : 'Mugu',
  'Simkot Rural Municipality' : 'Humla',
  'Namkha Rural Municipality' : 'Humla',
  'Chankheli Rural Municipality' : 'Humla',
  'Tanjakot Rural Municipality' : 'Humla',
  'Sarkegad Rural Municipality' : 'Humla',
  'Adanchuli Rural Municipality' : 'Humla',
  'Kharpunath Rural Municipality' : 'Humla',
  'Hima Rural Municipality' : 'Jumla',
  'Tila Rural Municipality' : 'Jumla',
  'Sinja Rural Municipality' : 'Jumla',
  'Guthichaur Rural Municipality' : 'Jumla',
  'Tatopani Rural Municipality' : 'Jumla',
  'Patrasi Rural Municipality' : 'Jumla',
  'Kanakasundari Rural Municipality':'Jumla',
  'Chandannath Municipality' : 'Jumla',
  'Mahawai Rural Municipality' : 'Jumla',
  'Palata Rural Municipality' : 'Kalikot',
  'Naraharinath Rural Municipality' : 'Kalikot',
  'Pachaljharana Rural Municipality' : 'Kalikot',
  'Subha Kalika Rural Municipality' : 'Kalikot',
  'Sanni Tribeni Rural Municipality' : 'Kalikot',
  'Khandachakra Municipality' : 'Kalikot',
  'Raskot Municipality' : 'Kalikot',
  'Tilagufa Municipality' : 'Kalikot',
  'Bhairabi Rural Municipality' : 'Dailekh',
  'Mahabu Rural Municipality' : 'Dailekh',
  'Gurans Rural Municipality' : 'Dailekh',
  'Naumule Rural Municipality' : 'Dailekh',
  'Bhagawatimai Rural Municipality' : 'Dailekh',
  'Thantikandh Rural Municipality' : 'Dailekh',
  'Dungeshwor Rural Municipality' : 'Dailekh',
  'Aathabis Municipality' : 'Dailekh',
  'Dullu Municipality' : 'Dailekh',
  'Chamunda Bindrasaini Municipality' : 'Dailekh',
  'Narayan Municipality' : 'Dailekh',
  'Kuse Rural Municipality' : 'Jajarkot',
  'Shiwalaya Rural Municipality' : 'Jajarkot',
  'Barekot Rural Municipality' : 'Jajarkot',
  'Junichande Rural Municipality' : 'Jajarkot',
  'Nalagad Municipality' : 'Jajarkot',
  'Bheri Municipality' : 'Jajarkot',
  'Chhedagad Municipality' : 'Jajarkot',
  'Tribeni Rural Municipality' : 'Western Rukum',
  'Sani Bheri Rural Municipality' : 'Western Rukum',
  'Banfikot Rural Municipality' : 'Western Rukum',
  'Aathbiskot Municipality' : 'Western Rukum',
  'Chaurjahari Municipality' : 'Western Rukum',
  'Musikot Municipality (Western Rukum)' : 'Western Rukum',
  'Kumakh Rural Municipality' : 'Salyan',
  'Darma Rural Municipality' : 'Salyan',
  'Kapurkot Rural Municipality' : 'Salyan',
  'Kalimati Rural Municipality' : 'Salyan',
  'Tribeni Rural Municipality (Salyan)' : 'Salyan',
  'Chhatreshwori Rural Municipality' : 'Salyan',
  'Siddha Kumakh Rural Municipality' : 'Salyan',
  'Sharada Municipality' : 'Salyan',
  'Bangad Kupinde Municipality' : 'Salyan',
  'Bagchaur Municipality' : 'Salyan',
  'Chaukune Rural Municipality' : 'Surkhet',
  'Simta Rural Municipality' : 'Surkhet',
  'Chingad Rural Municipali' : 'Surkhet',
  'Barahtal Rural Municipality' : 'Surkhet',
  'Gurbhakot Municipality' : 'Surkhet',
  'Panchpuri Municipality' : 'Surkhet',
  'Bheriganga Municipality' : 'Surkhet',
  'Lekbeshi Municipality' : 'Surkhet',
  'Birendranagar Municipality' : 'Surkhet',
  'Gaumul Rural Municipality' : 'Bajura',
  'Himali Rural Municipality' : 'Bajura',
  'Jagannath Rural Municipality' : 'Bajura',
  'Khaptad Chhededaha Rural Municipality' : 'Bajura',
  'Swami Kartik Khaapar Rural Municipality' : 'Bajura',
  'Badimalika Municipality' : 'Bajura',
  'Tribeni Municipality' : 'Bajura',
  'Budhiganga Municipality' : 'Bajura',
  'Budhinanda Municipality' : 'Bajura',
  'Masta Rural Municipality' : 'Bajhang',
  'Thalara Rural Municipality' : 'Bajhang',
  'Talkot Rural Municipality' : 'Bajhang',
  'Surma Rural Municipality' : 'Bajhang',
  'Saipaal Rural Municipality' : 'Bajhang',
  'Durgathali Rural Municipality' : 'Bajhang',
  'Bithadchir Rural Municipality' : 'Bajhang',
  'Kedarseu Rural Municipality' : 'Bajhang',
  'Khaptadchhanna Rural Municipality' : 'Bajhang',
  'Chabispathivera Rural Municipality' : 'Bajhang',
  'Jayaprithivi Municipality' : 'Bajhang',
  'Bungal Municipality' : 'Bajhang',
  'Lekam Rural Municipality' : 'Darchula',
  'Naugad Rural Municipality' : 'Darchula',
  'Byas Rural Municipality' : 'Darchula',
  'Dunhu Rural Municipality' : 'Darchula',
  'Marma Rural Municipality' : 'Darchula',
  'Apihimal Rural Municipality' : 'Darchula',
  'Malikaarjun Rural Municipality' : 'Darchula',
  'Mahakali  Municipality (Darchula)' : 'Darchula',
  'Shailyashikhar Municipality' : 'Darchula',
  'Sigas Rural Municipality' : 'Baitadi',
  'Shivanath Rural Municipality' : 'Baitadi',
  'Surnaya Rural Municipality' : 'Baitadi',
  'Dilasaini Rural Municipality' : 'Baitadi',
  'Pancheshwar Rural Municipality' : 'Baitadi',
  'Dogadakedar Rural Municipality' : 'Baitadi',
  'Melauli Municipality' : 'Baitadi',
  'Dasharathchanda Municipality' : 'Baitadi',
  'Purchaudi Municipality' : 'Baitadi',
  'Patan Municipality' : 'Baitadi',
  'Alital Rural Municipality' : 'Dadeldhura',
  'Ajaymeru Rural Municipality' : 'Dadeldhura',
  'Bhageshwar Rural Municipality' : 'Dadeldhura',
  'Nawadurga Rural Municipality' : 'Dadeldhura',
  'Ganayapdhura Rural Municipality' : 'Dadeldhura',
  'Amargadhi Municipality' : 'Dadeldhura',
  'Parashuram Municipality' : 'Dadeldhura',
  'Sayal Rural Municipality' : 'Doti',
  'Adharsha Rural Municipality' : 'Doti',
  'Jorayal Rural Municipality' : 'Doti',
  'Badikedar Rural Municipality' : 'Doti',
  'Purbichauki Rural Municipality' : 'Doti',
  'K I Singh Rural Municipality' : 'Doti',
  'Bogtan Foodsil Rural Municipality' : 'Doti',
  'Dipayal Silgadi Municipality' : 'Doti',
  'Shikhar Municipality' : 'Doti',
  'Dhakari Rural Municipality' : 'Achham',
  'Mellekh Rural Municipality' : 'Achham',
  'Chaurpati Rural Municipality' : 'Achham',
  'Ramaroshan Rural Municipality' : 'Achham',
  'Turmakhad Rural Municipality' : 'Achham',
  'Bannigadhi Jayagadh Rural Municipality' : 'Achham',
  'Sanphebagar Municipality' : 'Achham',
  'Mangalsen Municipality' : 'Achham',
  'Kamalbazar Municipality' : 'Achham',
  'Panchadewal Binayak Municipality' : 'Achham',
  'Chure Rural Municipality' : 'Kailali',
  'Janaki Rural Municipality' : 'Kailali',
  'Kailari Rural Municipality' : 'Kailali',
  'Joshipur Rural Municipality' : 'Kailali',
  'Mohanyal Rural Municipality' : 'Kailali',
  'Bardagoriya Rural Municipality' : 'Kailali',
  'Tikapur Municipality' : 'Kailali',
  'Ghodaghodi Municipality' : 'Kailali',
  'Bhajani Municipality' : 'Kailali',
  'Dhangadhi Sub-Metropolitian' : 'Kailali',
  'Gauriganga Municipality' : 'Kailali',
  'Godawari  Municipality (Kailali)' : 'Kailali',
  'Lamkichuha Municipality' : 'Kailali',
  'Beldandi Rural Municipality' : 'Kanchanpur',
  'Laljhadi Rural Municipality' : 'Kanchanpur',
  'Punarbas Municipality' : 'Kanchanpur',
  'Krishnapur Municipality' : 'Kanchanpur',
'Mahakali  Municipality (Kanchanpur)' : 'Kanchanpur',
'Bedkot Municipality' : 'Kanchanpur',
'Belauri Municipality' : 'Kanchanpur',
'Bhimdatta Municipality' : 'Kanchanpur',
'Shuklaphanta Municipality' : 'Kanchanpur',

  };


   List provienceList = <String>[];
   List districtList=<String>[];
   List muncipalityList =<String>[];
}
